local jelly = data.raw["item"]["jellynut-seed"]
local jellynut = data.raw["item"]["jellynut-seed"]

data:extend{{
	type = "plant",
	name = "halo-gmo",
	subgroup = jellynut.subgroup,
	order = jellynut.order .. "1",
	flags = {"placeable-neutral", "placeable-player", "placeable-off-grid", "breaths-air"},
	growth_ticks = 60*60*5,
	harvest_emissions = {spores = 15},
	agricultural_tower_tint = {primary = {1, 0.3, 0.1, 1}},
	pictures = {{
		size = {580,1024},
		filename = "__Solar-Halo__/gmo/plant.png",
		scale = 0.15,
		shift = {0, -2},
	}},
	max_health = 100,
	icon_size = 256,
	icon = "__Solar-Halo__/gmo/plant.png",
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-1, -4}, {1, 0}},
	minable = {
		mining_particle = "yumako-mining-particle",
		mining_time = 0.5,
		results = {{type = "item", name = "bioflux", amount = 100}},
	},
	build_sound = jellynut.build_sound,
	mining_sound = jellynut.mining_sound,
	mined_sound = jellynut.mined_sound,
	impact_category = jellynut.impact_category,
	placeable_by = {item = "halo-gmo", count = 1},
	tile_width = 3,
	tile_height = 3,
	map_color = {1,1,1,1},
	collision_mask = {
		layers = {
			object = true,
			player = true,
			transport_belt = true,
			resource = true,
			water_tile = true,
		},
	},
},{
	type = "item",
	name = "halo-gmo",
	order = jelly.order .. "1",
	subgroup = jelly.subgroup,
	stack_size = 10,
	icon = "__Solar-Halo__/gmo/icon.png",
	fuel_category = "chemical",
	fuel_value = "4MJ",
	place_result = "halo-gmo",
	plant_result = "halo-gmo",
	pick_sound = jelly.pick_sound,
	drop_sound = jelly.drop_sound,
	inventory_move_sound = jelly.inventory_move_sound,
	default_import_location = "gleba",
	weight = jelly.weight,
},{
	type = "recipe",
	name = "halo-gmo",
	category = "crafting-with-fluid",
	enabled = false,
	ingredients = {
		{type = "item", name = "yumako-seed", amount = 1},
		{type = "item", name = "jellynut-seed", amount = 1},
		{type = "fluid", name = "halo-compute", amount = 10000},
	},
	results = {{type = "item", name = "halo-gmo", amount = 1}},
	energy_required = 1,
	hide_from_player_crafting = true,
}}

